### ISSUE TITLE
Move API docs to loopback.io domain

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#133]
@bajtos suggested:

> Should we eventually move LoopBack's portion of  `apidocs.strongloop.com` to `apidocs.loopback.io`?

This would just be a DNS change, approved in principle by @ritch and @raymondfeng. 
However, it would be strange to have non-LoopBack docs on loopback.io, so we'd want to review the status of the API docs for:
- strong-cluster-connect-store
- strong-cluster-control
- strong-cluster-tls-store
- strong-mq
- strong-store-cluster
- strong-task-emitter

(see http://apidocs.strongloop.com/ for the content).

Can we eliminate the API docs and rely on the GitHub READMEs for the above? @sam-github

**Comment by sam-github** [comment]
@crandmck thumbs up for eliminating them from me, the READMEs are good enough, if anyone ever happens to use them.

**Comment by crandmck** [comment]
@rmg What's involved with switching the DNS for http://apidocs.strongloop.com/ to http://apidocs.loopback.io/ ?

**Comment by rmg** [comment]
- [ ] add `loopback.io` to out bluemix account
- [ ] add `apidocs` record to `loopback.io` zone
- [ ] add `apidocs.loopback.io` as a route for the apidocs app
- [ ] buy an SSL certificate for `apidocs.loopback.io` or `*.loopback.io`
- [ ] add SSL cert to bluemix account

All of these are trivial _except_ for buying the certificate. Unfortunately we cannot use CloudFlare's free SSL for this (policy related, not technical), and I'm not sure what the process is for getting SSL certs.

**Comment by crandmck** [comment]
@chandadharap What's the process for getting SSL certs?

**Comment by sam-github** [comment]
@rmg --^

**Comment by bajtos** [comment]
Makes me wonder: can we use Let's Encrypt to get a free SSL certificate?

**Comment by rmg** [comment]
Let's Encrypt is based on ACME, which is a verification protocol that requires control of the host. Control of the host shifts a whole bunch of operational and policy responsibilities (aka overhead) onto our (my?) plates. Right now we are able to avoid that complexity by hosting apidocs.strongloop.com on a PaaS (Bluemix) and loopback.io on GH Pages.

Free SSL from CloudFlare is tied to terms of service that have been deemed unacceptable, so that isn't an option either.

**Good news:** I managed to track down how to buy certs. Since we aren't likely to have dozens of subdomains, our best bet is probably a multi-SAN certificate, which would allow us to use a single cert for multiple domains and subdomains. There's additional cost after 4 names, but still a long way from a wildcard and has the advantage of supporting multiple domains if we want.

**Comment by crandmck** [comment]
Cool, so what's the upshot?  Can we do this?  If so, when?

**Comment by rmg** [comment]
@crandmck let's discuss the specifics elsewhere since they involve IBM resources and this is a public repo. We can summarize the results here after.

**Comment by dhmlau** [comment]
@crandmck , looks like this is done.  is it good to close? Thanks.

**Comment by crandmck** [comment]
Yes! :-D
