### ISSUE TITLE
Default to simple English URLs

### ISSUE THREAD

**Issue by superkhau** [loopbackio/loopback.io#215]
As discussed in standup awhile ago, we should default the doc pages to English without the i18n modifier in the path. For example, if I want to get the to community page, it should be as simple as:

```
loopback.io/community
```

And for other languages, say Chinese:

```
loopback.io/cn/community
```

So the country identifier isn't there for the default English URLs.

**Comment by crandmck** [comment]
The way we do this is to add the following (for example) in each affected page's front-matter:
```
redirect_from:
- /community/
```
I committed the above example, so now http://loopback.io/community/ redirects to http://loopback.io/doc/en/community/index.html.

Please list other pages for which you would like a redirect.  I think it's fine for some pages where it's nice to have a short easy-to-remember URL, such as the above, but I'd prefer not to do it for every single page on the site, since I think that has limited utility.

**Comment by superkhau** [comment]
@crandmck Great, I think we'll have to do this on a case-by-case basis then. We can close this issue since you have a way of redirecting easily. ;) I will open up new 1 point issues when those times come so we can do async. However, if you have time, here are some obvious ones off the top of my head:

- [ ] `/examples` should redirect to https://loopback.io/doc/en/lb2/Tutorials-and-examples.html
- [x] `/style-guide` should redirect to http://loopback.io/doc/en/contrib/style-guide.html

**Comment by crandmck** [comment]
http://loopback.io/examples/ is already taken.  Can you suggest another mnemonic URL for that page?
Maybe `/example-apps` ?

> I will open up new 1 point issues when those times come so we can do async.

That's fine, though it's so simple to create a redirect that just opening a PR would also be OK and would save a bit of time.

**Comment by superkhau** [comment]
>That's fine, though it's so simple to create a redirect that just opening a PR would also be OK and would save a bit of time.

Even better, I don't mind submitting PRs. Can you link to an example PR here so we have something to refer to next time?

>http://loopback.io/examples/ is already taken.

I'm proposing we move the current content (which is really a showcase of features) to another section (maybe `/features` or `/discover`) and free up `/examples` for actual examples.

For now though, how about redirecting both `/tutorials` and `/example-apps`?

**Comment by crandmck** [comment]
> I'm proposing we move the current content (which is really a showcase of features) to another section (maybe /features or /discover) and free up /examples for actual examples.

This is fine by me, but because the site has been around for a few years, there may be some existing links (e.g. on strongloop.com, blogs, etc) that we'll need to change accordingly.  And IAC, we'll need to check with @chandadharap and @sumitha before doing this.

> For now though, how about redirecting both /tutorials and /example-apps?

Done by #221, so I'll go ahead and close this.
