### ISSUE TITLE
Creating remote instance methods documentation

### ISSUE THREAD

**Issue by ahallez** [loopbackio/loopback.io#220]
http://loopback.io/doc/en/lb3/Remote-methods.html

When creating a remote method, according to the documentation the method is created non-static if the method name is preceeded by prototype.

However, when trying this out, I noted that the method is created static by default.
For creating a non-static method, you have to add isStatic: false to the method options.

**Comment by crandmck** [comment]
Yes, the migration guide states that remote methods are static by default: http://loopback.io/doc/en/lb3/Migrating-to-3.0.html#update-remote-method-definitions but we should also add that in the above doc and release notes.

Actually, I notice that it says this:
>  A method name starting with `prototype.` indicates an instance method; otherwise, it’s a static method.

So that basically says it, but I can try to emphasize and clarify.

> For creating a non-static method, you have to add isStatic: false to the method options.

That's true in LoopBack 2.x, but in 3.0 (as stated in release notes and migration guide), `isStatic` no longer works.

**Comment by crandmck** [comment]
Addressed with 17270de8a8bdc8d1609abd5a2ce4a1383d950652
