### ISSUE TITLE
Clarify how to define datasources programmatically

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#331]
From @timlind comment in https://github.com/strongloop/loopback.io/pull/317#issuecomment-285854277:

> ...defining data sources programatically, [... is ... ] really tricky.

 > If you play around with my sandbox (timlind@be72636), just trying to follow the docs that use new DataSource(), it's not clear where to define datasources (bootscript? how does it integrate with a custom migration.js bootscript?), where to associate models (why does model-config.js not work?), and what the interaction is if the same datasource is partially defined in datasources.json (can model-config.js be used then?), if attaching models programmatically, this should be done somewhere other than model.js where boot scripts have not been run and datasources have not been defined.

Clarify in http://loopback.io/doc/en/lb3/Advanced-topics-data-sources.html

**Comment by ebarault** [comment]
Thanks @crandmck for keeping track of this.

I've been thinking about this recently: in the tests we often define datasources programmatically, but when doing this, we then define everything else by code (e.g. attaching models to ds), we don't mix datasources defined by code and config file (json or js).

Maybe this should be the correct way to address this doc improvement (before opening another pandora box).
@bajtos : what do you think?

**Comment by bajtos** [comment]
To be honest, I don't really understand what is the motivation for creating datasources via JS API. loopback-boot provides many ways how to dynamically define datasource configuration, from environment variables in JSON file to the ability to provide a javascript file to build the datasource configuration, e.g. `datasources.production.js`.

---

IMO, the page http://loopback.io/doc/en/lb3/Advanced-topics-data-sources.html describes the low-level loopback-datasource-juggler API. In LoopBack, we typically use a different API:

```js
const app = loopback();

// create a data source
app.dataSource('db', { connector: 'memory' });

// create a model
app.registry.createModel({
  name: 'Customer',
  base: 'User',
  properties: {
    isPreferred: { type: 'boolean' },
  },
});

// attach a model to a datasource
// and expose it via REST API
app.model(Customer, { dataSource: 'db' });
```

As for mixing datasources defined by code with datasources and models defined by loopback-boot from JSON configuration, it's important to understand how loopback-boot works under the hood. With that knowledge in hand, users should be able to answer the questions in this issue's description themselves.

Here is how loopback-boot@2.x works (see [lib/executor.js](https://github.com/strongloop/loopback-boot/blob/9cb3d0648b7d39e17e1e3e47ff26a098c44a3754/lib/executor.js#L38-L39)):

 1. All datasources defined in `datasources.json` are created by calling `app.dataSource` as shown above.
 2. `model-config.json` is analysed to determine which models need to be loaded (e.g. when `Customer` extends `User`, we need to load `User` first and then `Customer` second) and attached to the application (e.g. `Customer` is attached, `User` is not).
 3. All models are loaded - the JSON config is passed to `app.registry.createModel`, then the customization script is run.
 4. All entries from `model-config.json` are executed - models are attached to the application via `app.model`.

> it's not clear where to define datasources (bootscript? how does it integrate with a custom migration.js bootscript?)

In loopback-boot@2, custom datasources must be defined before `boot(app)` is called - i.e. the user has to manually modify `server/server.js`.

> where to associate models (why does model-config.js not work?)

`model-config.json` works as long as the datasource was defined before `boot(app)` was called.

`model-config.js` is not supported, this was an intentional design decision. See https://github.com/strongloop/loopback-boot/pull/125, https://github.com/strongloop/loopback-boot/issues/80 and https://github.com/strongloop/loopback-boot/issues/93.

> what the interaction is if the same datasource is partially defined in datasources.json

What do you mean by partial definition of a datasource?

> if attaching models programmatically, this should be done somewhere other than model.js where boot scripts have not been run and datasources have not been defined.

As I wrote before, if you want to define datasources via JS API, then you have to do it before `boot(app)` was called by your `server/server.js`.

---

Note that loopback-boot@3 has slightly different design and certain things may work differently from what I described above. For example, it may be possible to write a boot script that's run before models and datasources are defined, if I remember correctly. I'll leave it up to @raymondfeng and @davidcheung to explain, as they know the upcoming major version best.

**Comment by ebarault** [comment]
@bajtos : many thanks for such a detailed answer.
(Now i'm feel guilty for your invested time)

To me the doc in http://loopback.io/doc/en/lb3/Advanced-topics-data-sources.html can only mislead LoopBack users and make them feel extra configuration is required. As you said there are many options offered that make this unnecessary.

Shouldn't this just be removed from Loopback.io and kept only in the juggler's api doc?

**Comment by bajtos** [comment]
> many thanks for such a detailed answer. (Now i'm feel guilty for your invested time)

Don't feel guilty at all! I think this matter was never described comprehensively, I took this discussion as the opportunity to correct that.

**Comment by crandmck** [comment]
I would note that @raymondfeng wrote the original content of this article (IIRC) several years ago.  It may or may not be that relevant any more. 

> I don't really understand what is the motivation for creating datasources via JS API. 

This is the crux of the issue.  Are there any valid use-cases for doing this?  

If so, we should enumerate them and note that they are (I presume) advanced or specialized cases.

If not, then we should consider:

> Shouldn't this just be removed from Loopback.io and kept only in the juggler's api doc?

Instead of removing it altogether, we could add a caveat that this article explains the Juggler API for general background and perhaps unanticipated use cases, but is not important for most people who can use JSON instead.

**Comment by bajtos** [comment]
@raymondfeng @ritch could you please chime in and let us know your opinion?

**Comment by nlgonzalez** [comment]
@crandmck I have an scenario where I use Vault to provide the configurations for the datasource of the loopback app running inside a docker container.
Im implementing this so that before I run the  boot(app) in server.js the vault client is called and create the datasource. 

I know it can be done by setting Env variables but I think is better to just provide the vault token an allow the setup of the server to configure the datasource. I think this would be a valid use-case, do you have other way to implement this? ( I have also experimented with creating the "datasources.json" using a sh script.)

**Comment by crandmck** [comment]
Hi @nlgonzalez I'm not familiar with Vault... I presume you're referring to https://hub.docker.com/_/vault/, yes?

I'm not the best person to address this--perhaps @bajtos or @kjdelisle can do so...?

**Comment by nlgonzalez** [comment]
@crandmck Exactly! We are using vault as our secret repository I can share how I implemented it to se if it makes sense. Thanks!

**Comment by bajtos** [comment]
@nlgonzalez The `boot` function implemented by `loopback-boot` allows callers to provide custom datasource configuration object that should be used instead of content from `datasources.json` file(s). See http://apidocs.strongloop.com/loopback-boot/#boot

Here is a mockup to illustrate my point:

```js
// in server/server.js
fetchDataSourceConfigFromVault((err, config) => {
  if (err) throw err;

  boot(
   app,
    {
      appRootDir: __dirname,
      dataSources: config,
    },
    (err) => {
      if (err) throw err;

      // start the server if `$ node server.js`
      if (require.main === module)
        app.start();
      });
   });
});
```

**Comment by nlgonzalez** [comment]
@bajtos thanks for the info! Works great!

**Comment by bajtos** [comment]
@nlgonzalez that's great to hear! Would you mind contributing this information to our documentation, so that other users can find it more easily? See http://loopback.io/doc/en/contrib/doc-contrib.html to get you started.

cc @crandmck

**Comment by crandmck** [comment]
Probably http://loopback.io/doc/en/lb3/Advanced-topics-data-sources.html#creating-a-data-source-programmatically is the best place... Or perhaps http://loopback.io/doc/en/lb3/Defining-data-sources.html.
