### ISSUE TITLE
Mistakes in documentation

### ISSUE THREAD

**Issue by GHNewbiee** [loopbackio/loopback.io#382]
1) http://loopback.io/doc/en/lb3/LoopBack-FAQ.html

"StrongLoop also publishes a blog with topics relevant to LoopBack. See Blog posts for a list of the latest posts."

https://strongloop.com/strongblog/category/loopback-2/ **page does not exist**.

2) http://loopback.io/doc/en/lb3/Create-a-simple-API.html

"Now that you’ve scaffolded the initial project, you’re going to create create a CoffeeShop model that will automatically have REST API endpoints."

"create" word is **doubled**.

3) http://loopback.io/doc/en/lb3/Managing-users.html

"In addition, LoopBack does not support multiple models based on the User model in a single application. That is, you cannot have more than one model derived from the built-in User model in a single app."

**This is not true anymore.**

4) http://loopback.io/doc/en/lb3/Customizing-models.html

"You can create custom models that extend from a single base custom model. For example, to define a model called MyModel that extends from a custom model you defined called mMyBaseModel, create MyModel using model generator then edit the JSON file common/models/MyModel.json as follows:
/common/models/model.json
{ ... }
You can add new properties when you extend a model, for example:
/common/models/model.json
{ ... }"

mMyBaseModel should be **MyBaseModel**, two "model.json" file names should be "**MyModels.json**"

**Comment by GHNewbiee** [comment]
5. http://loopback.io/doc/en/lb3/Next-steps.html

"LoopBack documentation includes lots of tutorials and examples; also read the StrongLoop blog for great tips and information."

Substitute the following link **strongloop.com/strongblog/** with this one **strongloop.com/strongblog** w/o "/" in the end.

**Comment by crandmck** [comment]
Thanks @GHNewbiee for catching these issues.  I'll fix them.  We just relaunched a new strongloop.com site yesterday, so that's the source of the issues with those links.  IAC, I'll fix the broken links.

> LoopBack does not support multiple models based on the User model in a single application. That is, you cannot have more than one model derived from the built-in User model in a single app.
> This is not true anymore.

Strictly speaking, you're correct. I will clarify this.  What it should say is that an app can use only one User-based model for login and auth; although you _can_ have multiple User-based models, only one is use for generating auth tokens and the like.

**Comment by crandmck** [comment]
Fixed by 66fcb5395b2925ddcb9490b97993b82b2d72f9ab.

**Comment by GHNewbiee** [comment]
"... an app can use only one User-based model for login and auth; although you can have multiple User-based models, only one is use for generating auth tokens and the like."

**That's very disappointing!!!**

Imho, customers and employees exist in **different** schemes and should **login** and **be authenticated** through **different** channels for **security** reasons!

Please, ask coordinating team to reconsider the fact and give the freedom to the people from the beginning!

**Comment by crandmck** [comment]
@GHNewbiee Would using [realms](http://loopback.io/doc/en/lb3/Partitioning-users-with-realms.html) help at all to address your concerns?

@raymondfeng ^

**Comment by GHNewbiee** [comment]
Imho,

_realms_ should be a step **ahead** of what it is supposed to be used for now.

_customer_, _employee/administrator_ (at least) and _supplier_ are two or three entities with different properties. _realms_ could be used for further partitioning of each entity.

"By default, the LoopBack User model manages all users in a global namespace." This is the **weakness.**.
There should be an option in _config.json_ for global namespace or multiple namespaces set manually or automatically .

"A user or application can belong to only one realm." This is another **restriction** imposed by the construction of _realms_.

I think that every User-based model could be able to be used for generating auth tokens and the like. Consider the example below:
There is a building e.g. Trump Tower: It has a main entrance. All customers goes through this entrance for security control. In the parking there is another entrance through which the employees pass security control. In the backyard, there is another entrance for suppliers with trucks to discharge the goods. In your way, there is one entrance through which customers, employees and suppliers with goods go! At the entrance you give to each one a label card. You are _realms_: customer, _realms_: employee, and _realms_: supplier.

**Comment by GHNewbiee** [comment]
6. http://loopback.io/doc/en/lb3/datasources.json.html

"To connect a model to a data source, follow these steps to create a datasource."

The link https://loopback.io/doc/en/lb2/datasources.json.html#properties-for-database-connectors reffers to lb2 documentation.

7. http://loopback.io/doc/en/lb3/datasources.json.html

"  connector 	LoopBack connector to use:
    ...
    loopback-storage-service
    Another LoopBack data source connector"

loopback-storage-service should be changed into loopback-component-storage.

**Comment by GHNewbiee** [comment]
8. http://loopback.io/doc/en/lb3/Updating-to-the-latest-version.html

There is not any reference on the left ToC. You can only visit this page through a link on another page.

**Comment by GHNewbiee** [comment]
9. http://loopback.io/doc/en/lb3/Installing-compiler-tools.html

There is not any reference on the left ToC. You can only visit this page through a link on another page.

**Comment by GHNewbiee** [comment]
10. http://loopback.io/doc/en/lb3/User-management-example.html

"common/models contains the extended user files. user.js **contains user the logic ** for sending emails and password reset, while user.json contains the model definition."

Syntax error.

**Comment by crandmck** [comment]
Re: input on realms:
Suggest you open an issue in [loopback](https://github.com/strongloop/loopback) to start a discussion.  Since this repo is just for docs, your comment is unlikely to be noticed here.

Re: comments on http://loopback.io/doc/en/lb3/datasources.json.html and http://loopback.io/doc/en/lb3/User-management-example.html.  
Yes, those are mistakes. I will correct, and thank you for finding them.

Re: http://loopback.io/doc/en/lb3/Updating-to-the-latest-version.html and  http://loopback.io/doc/en/lb3/Installing-compiler-tools.html

These articles are intentionally omitted from the navigation sidebar, because `loopback-cli` does not require installing compiler tools, per the warning:

> Warning: The StrongLoop slc tool is still available, however it is not recommended for LoopBack development, as it will be deprecated in the future. ...

I didn't remove them because there may still be external links to them, even though they are not strictly required any longer, since the docs now focus on using `lb` instead of `slc`.  But looking  again, some of the info in "Updating to the latest version" may still be useful.  It probably makes sense to add that to "Installation" and "Installation Troubleshooting".  Thanks for bringing it to my attention.
