### ISSUE TITLE
Add docs for loopback-connector-mailgun

### ISSUE THREAD

**Issue by atherdon** [loopbackio/loopback.io#389]
## URL of the page 
https://loopback.io/doc/en/lb3/Email-connector.html

## Nature of the issue 

I came to this page and I think it can be improved by adding information about how to use MailGun connector.
For me personally, its more easy to setup a MailGun for my test purposes, rather than to use my Gmail address. It's also better, because I don't need to enable on my gmail option to send "outer" emails.
I can create a pull request for this update.

**Comment by crandmck** [comment]
Thanks @atherdon, a PR would be great.

The [Email connector](https://loopback.io/doc/en/lb3/Email-connector.html) page is meant to explain the built-in email connector.   Rather than documenting how to use loopback-connector-mailgun there, I suggest the following:

- Add it to the table in http://loopback.io/doc/en/lb3/Community-connectors.html
- Add it to [Community Projects](http://loopback.io/doc/en/community/index.html).  See [How to add a community project](http://loopback.io/doc/en/community/How-to-add-a-project.html)
- Add a cross-reference (link) in [Email connector](https://loopback.io/doc/en/lb3/Email-connector.html.

**Comment by atherdon** [comment]
I'm starting to doing this. Will submit PR soon

**Comment by crandmck** [comment]
Thanks!  I'll be out on vacation for the next two weeks, and I suggest @bschrammIBM review this PR when it's ready...

Also, perhaps @bajtos could take a look at a technical angle.

**Comment by atherdon** [comment]
Ok, thanks @crandmck ! Have a good vacation!
I was stuck with second item( Add MailGun connector to Community projects), but I hope I'll be able to solve it too, and then I'll submit a PR with commits, related to this issue.

Arthur
