### ISSUE TITLE
APIdocs

### ISSUE THREAD

**Issue by Cyperwu** [loopbackio/loopback.io#437]
## URL of the page 

[ACL](https://apidocs.strongloop.com/loopback/#acl)

## Nature of the issue 

inaccurate documentation content.

in the **Class Properties** form, row 5, ** principalType**

original: ``` Type of the principal; one of: Application, User, Role.```

will misguide developers (such as me)

## Expected behavior

should be: ``` Type of the principal; one of: APPLICATION, USER, ROLE.```

I silmply cant find where to raise this Issue so I make it here.

**Comment by crandmck** [comment]
Thanks @Cyperwu this is the right place to raise the issue.
Just to confirm, the only problem is that these string values should be capitalized; is that right?

**Comment by Cyperwu** [comment]
@crandmck Yep, totally. spent me a few hours.

**Comment by crandmck** [comment]
Fixed by https://github.com/strongloop/loopback/pull/3559
@Cyperwu If you're interested in fixing or contributing to API docs in the future, have a look at what I did (trivial PR).

Also, note that the changes won't appear on https://apidocs.strongloop.com/loopback/ until the loopback package is republished to npm.

**Comment by Cyperwu** [comment]
@crandmck Okay, I'll check it out.
