### ISSUE TITLE
how can i start translate en version?

### ISSUE THREAD

**Issue by qxl1231** [loopbackio/loopback.io#48]
i find all branch, there is nothing of en version page(only demo page).so i need to write the page all?i'm confused...
please show me the guide. thank you

**Comment by crandmck** [comment]
Hi @qxl1231 As I mentioned several times previously, we are not ready yet for translation.  The English content still has lots of issues (broken links, missing tags, formatting / layout, etc.).   Since your starting point will be the English content , we want to ensure that it's in acceptable shape before beginning any translation.  

So, please just be patient.  I'm working as fast as I can to clean up the English content, and I will notify in #38 and post instructions for translators.

If you want to help, please take a look at #47, because that will affect any translations to languages that use non-Western character sets, including Chinese.  Currently, this is a blocker for localization.  I don't know how to resolve this right now.

**Comment by qxl1231** [comment]
now zh/  chinese version can translate ?

**Comment by crandmck** [comment]
We do have SOME old Chinese translation imported from the old site: http://loopback.io/doc/zh/lb2/
However, it may be a bit outdated.  Since I can't read Chinese, I have no idea! :-)
I do think that some of the links are broken, etc.

If you want to remove any of the old/existing Chinese articles and just replace them with new translations, that's fine. 

Here is the basic translation process: http://loopback.io/doc/en/contrib/Translating_articles.html.
Let me know if you have any questions...and thanks!
