### ISSUE TITLE
Make LB4 GitHub repo + Welcome Contributors messages visible

### ISSUE THREAD

**Issue by dhmlau** [loopbackio/loopback.io#488]
Follow on discussion from https://github.com/strongloop/loopback.io/pull/487#issuecomment-336450889
> I'm wondering how our users would find out our LBNext repo link

> That's a very good point! I think we should start by improving the LB4 landing page (http://loopback.io/doc/en/lb4/) to contain a link to the GitHub repo. Possibly with few more links, e.g. to Welcoming Contributors and Extensions!.

related to: https://github.com/strongloop/loopback.io/pull/487

/cc @bajtos

**Comment by dhmlau** [comment]
For the github link on loopback.io, I'm thinking whether it would be good to put the github link icon somewhere inside "COMING SOON" message box.  
Don't know if it's going to confuse people because we have the github link to `loopback` repo at the top right corner of the page.

**Comment by crandmck** [comment]
I think it would be better to direct them to the doc page (http://loopback.io/doc/en/lb4/index.html) then add a link on that page to the lb-next repo.  The doc page will give them a bit more context and the opportunity to dig into the docs if they want.

**Comment by crandmck** [comment]
I was going to open a PR, but I accidentally committed my edits: http://loopback.io/doc/en/lb4/
I didn't think it was worth it to back out the change and do it via PR, since we can just refine it on the site IMO since we're still pre-beta.

I added the right-aligned "box" with a link to the repo, and I also thought it worth a brief mention  that we're using a "mono repo" instead of many repos as before.

LMK if you'd like changes to the text, layout, etc.

**Comment by bajtos** [comment]
> I added the right-aligned "box" with a link to the repo, and I also thought it worth a brief mention that we're using a "mono repo" instead of many repos as before.

👏 

> _Components will be in their own individual repositories, however._

I am not sure if this is true. For example, `@loopback/authentication` is living inside mono repo.

We haven't discussed this yet in depth, but I think all components maintained by us should live in the main mono repo too, for the same reasons why we moved core components to the mono repo - we want to have most of the code we are maintaining in one repo to make cross-project changes easier. Only components contributed by our community should have their own github repositories and projects.

In addition to components, we are keeping some examples in standalone repositories to make these examples easier to use, since they are typically consumed via `git clone`, which does not support fetching a sub-directory (sub-package) from a mono repo.

That's the long story, I am not sure how to convert this information into a brief sentence for your new "box".

**Comment by crandmck** [comment]
How about "Examples and externally-developed components will be in separate repositories" ?

**Comment by bajtos** [comment]
> How about "Examples and externally-developed components will be in separate repositories" ?

Sounds good 👍

**Comment by crandmck** [comment]
OK, I made that change to http://loopback.io/doc/en/lb4/.
Can we close this now?

**Comment by dhmlau** [comment]
LGTM. thanks.
