### ISSUE TITLE
Docs: USING CONFIG.JSON IN LOOPBACK 4

### ISSUE THREAD

**Issue by daniDevKr** [loopbackio/loopback.io#540]
In `Loopback 4` can you use the file `server/config.json`?
How do I load the configuration from this file?
Help me please ! 👍

**Comment by b-admike** [comment]
Hi @jhonToni, how do you want to use `server/config.json` and what is in it? Nonetheless, you can use a similar approach as [here](https://github.com/strongloop/loopback4-example-getting-started/blob/master/src/datasources/db.datasource.ts#L5-L14).

**Comment by kjdelisle** [comment]
@jhonToni LoopBack 4 does not have a `config.json` concept in the same way that LoopBack 3 does.

Since LoopBack 4 makes use of the concept of Servers as distinct objects that you configure separately from the top-level Application context, we can't have a "master" config location to setup your server details, because you can have any number of them.

http://loopback.io/doc/en/lb4/Application.html#making-your-own-application-class

In the above link, there's a small piece demonstrating some of the context binding for setting a RestServer's port.

Expanding on the example, let's add a 2nd Admin server into the mix.
I've removed the other comments from the example for clarity and highlighted the different parts.

```ts
import {Application} from '@loopback/core';
import {RestComponent, RestServer} from '@loopback/rest';
import {SamoflangeController, DoohickeyController} from './src/controllers';
// We're adding our AdminApi definition file to this import.
import {WidgetApi, AdminApi} from './apidef/';

export class WidgetApplication extends Application {
  constructor() {
    super({
      components: [RestComponent],
    });
    const app = this; // For clarity.
    app.controller(SamoflangeController);
    app.controller(DoohickeyController);

    // We'll create a 2nd server instance that will host our administrative API on a private port.
    app.server(RestServer, 'adminServer');
  }

  async start() {
    const server = await app.getServer(RestServer);
    server.bind('rest.port').to(80);
    server.api(WidgetApi);

    const adminServer = await app.getServer('adminServer');
    // In this example, you'd refuse external traffic on 8080.
    adminServer.bind('rest.port').to(8080); 
    adminServer.api(AdminApi);
    return await super.start();
  }

  async stop() {
    console.log('Widget application is shutting down...')
    await super.stop();
  }
}
```

This new philosophy gives us much greater flexibility with respect to _how_ you can configure your application. 

We could have made a monolithic configuration file that performed the same actions, but anyone who's keen to build something like that can easily create their own file loader and inject the values from their config file into their application using this approach.

Rolling our own config.json specification would also mean that if you wanted something the existing design didn't account for, then you'd have to spend time extending our hypothetical configuration class(es) to get the same results.

**Comment by bschrammIBM** [comment]
I am tagging this for a doc update as it provides a good use case.

**Comment by daniDevKr** [comment]
How can I set   the accepted  `content-types` of the  `post requests`  ??

**Comment by ashtrisk** [comment]
How can I add a common prefix to all API path e.g. /api/v1 in Loopback 4?
