### ISSUE TITLE
Change in docs referring Bluemix (currently known as IBM Cloud)

### ISSUE THREAD

**Issue by dhmlau** [loopbackio/loopback.io#545]
With the name of Bluemix has changed to IBM Cloud (https://www.ibm.com/blogs/bluemix/2017/10/bluemix-is-now-ibm-cloud/), we might want to change the Bluemix references to `IBM Cloud`.

Examples of pages that need to be changed: 
https://loopback.io/doc/en/lb2/LoopBack-on-Bluemix.html
https://loopback.io/doc/en/lb3/Bluemix-config-generator.html
https://loopback.io/doc/en/lb3/Command-line-tools.html
https://loopback.io/doc/en/lb2/Cloudant-connector.html
and more...

cc @DaveYVR

**Comment by dhmlau** [comment]
@bschrammIBM , do you think you could help us with the renaming?  Thanks.

**Comment by bschrammIBM** [comment]
Yes will do - here are some clarification points:
1) Does this need to be done in LB2?
Due to time constraints for me, might be best to update LB3 only to accommodate the name change from Bluemix to IBM Cloud.
2) I do not plan to change any filenames and also the links that contain the term 'Bluemix'; only when the term is used in the text.

**Comment by bschrammIBM** [comment]
this has been completed in commit 71744eddb514faea3c5110a50b197c5f1a1a5de1
completed in LB3 only
closing this
