### ISSUE TITLE
Spanish translations for the documentation

### ISSUE THREAD

**Issue by 0xJuancito** [loopbackio/loopback.io#72]
Are you planning spanish translations for the documentation? I don't see the option in the Translations menu

If so, i could help with that!

**Comment by crandmck** [comment]
We don't have any specific plans for translations.  At this point, it's up to the community.  Your help is welcome!

>  I don't see the option in the Translations menu

We haven't added it yet.  Follow the instructions in  http://loopback.io/doc/en/contrib/Adding_a_new_language.html to add it.  Let me know if you need any help.

NOTE: We in the process of changing the format of the sidebar `.yml` files slightly (see #73).   So, you should probably wait a day to start on this.  We should be done in a day or so.

**Comment by crandmck** [comment]
@juanscolari If you want me to add a "space" for Spanish language, just let me know and I'll do that. 

If you have any specific questions, want to involve anyone else in the community in the Spanish translation effort, or have any other reason to keep this issue open, please comment here.  
Otherwise, I'll close this issue--thanks!

**Comment by juanscolari** [comment]
I was waiting for #73 to be closed to start with the sidebar. I have just seen that it was merged. Closing this!
