### ISSUE TITLE
Using hasMany and belongsTo together

### ISSUE THREAD

**Issue by ghmendonca** [loopbackio/loopback.io#739]
When I define a hasMany relation from model A to model B, it works just fine, I can use the "include" filter to include the B's that belongs to A. But, with only this, I can't include A from B, so when I query B and try to include A, it says that the relation is not defined, and it's correct.

If I do the opposite way, define that B belongs to A, it works just fine too, I can now include the A model from my B's models. But with this way, I can't include my B's from my A.

If I mix both, define in A model the hasMany to B relation and in B model define the belongsTo A, and try to query all A including all B's that belongs to each A, doesn't work, always returns a empty array.. But if I try to query B and include A, works just fine.

So, how I can achieve this? I really need the two way includes working.

Just to avoid some questions, I already read the docs and couldn't find the solution. The hasManyThrough isn't the solution, because it defines a many-to-many relation as the docs says, I just want a hasMany that I can use the include filter in both models.

**Comment by b-admike** [comment]
@ghmendonca Thank you for explaining the issue. Can you provide us a sandbox application which showcases the issue or perhaps use https://github.com/strongloop/loopback-example-relations to do it since it defines a two way relation for `Customer` and `Order` models (i.e. Customer has many orders and Order belongs to Customer)?
