### ISSUE TITLE
hiding api for users not allowing to login loopback

### ISSUE THREAD

**Issue by ri8ika** [loopbackio/loopback.io#799]
I am just learning loopback (version 3x). And was following [this tutorial](https://loopback.io/doc/en/lb3/Tutorial-access-control.html). 

The tutorial states to hide the api for users:

`Expose via REST: No`

I thought, it would just not display in the explorer. But I am also not able to login through any means. For eg. I tried to login from postman. It says there's no method.

When I expose the api for users then only I'm able to login.

So, I have few questions:

How to access for hidden api?
Or, must I publicly expose the api `public:true`?
Is the tutorial stating someway wrong?
What is the purpose of hiding api if it doesn't allow to access?

Thanks.

**Comment by jannyHou** [comment]
@ri8ika "Hiding the api" means there is no http endpoint exposed for the corresponding model's functions, e.g. `GET Users/{id}` won't be exposed for `User.findById()`, which means `GET Users/{id}` doesn't exist. 
That's why whichever tool you use, postman or curl, doesn't make a difference.

LoopBack defines a set of REST functions for persisted model, like `find()`, `findById()`, `patch()`, `delete()`, and expose corresponding REST endpoints for them, by hiding an endpoint, those REST functions are still there.

**Comment by ri8ika** [comment]
@jannyHou Thanks for your reply.

Okay, hiding api for `/users` will not allow to perform its method. But,  shouldn't we also be able to login? Please check the tutorial I have linked and let me know.

Thanks again.

**Comment by bajtos** [comment]
@ri8ika To hide a method from REST API Explorer, but keep it still accessible to clients, one can set `documented: false` in remoting metadata of such method. 

Here is a mock-up to illustrate what I mean, it may not work out of the box.

```js
// put this script to server/boot/hide-login.js
module.exports = function(app) {
  app.models.User.findMethodByName('login').documented = false;
}
```

**Comment by dhmlau** [comment]
Closing as resolved.
